services:
  scrapper-ent:
    build: .
    image: scrapper-ent:latest
    environment:
      IDENTIFIANT: ${IDENTIFIANT}
      MOT_DE_PASSE: ${MOT_DE_PASSE}
    volumes:
      - ./:/app
    # Pour la d√©sactivation du sandboxing si besoin:
    # cap_add:
    #   - SYS_ADMIN
